language: node_js
node_js:
- stable

deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script: bash deploy.sh

before_install:
- openssl aes-256-cbc -K $encrypted_504acce1fa8e_key -iv $encrypted_504acce1fa8e_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SH\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $SU@SH pwd

