name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBECONFIG }}
        id: setcontext

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.2'
        id: kubectlinstall

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'
        id: helminstall

      - run: ./release.sh