name: Server Restart

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 10 * * *'

jobs:
  restart-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBECONFIG }}
        id: setcontext

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.2'
        id: kubectlinstall

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'
        id: helminstall

      - run: |
          helm repo add itzg https://itzg.github.io/minecraft-server-charts/
          helm upgrade minecraft --install --set "minecraftServer.forceReDownload=true" -f values.yaml itzg/minecraft
